version: 2.1

orbs:
  docker:
  image: circleci/python@0.2.1

jobs:
  test_yahoo_data:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
         command: |  # use pipenv to install dependencies
          sudo pip install pipenv
          pipenv install
      - run:
          command: python -m pytest --ticker=SQ --junitxml=tests/test-results/results.xml

          name: Test
      - store_test_results:
          path: tests/test-results
workflows:
  main:
    jobs:
      - test_yahoo_data