version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test_yahoo_data:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Install dependencies
          command: pipenv install
      - python/install-packages:
          args: pytest
          pkg-manager: pipenv
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run Tests
          command: python -m pytest --ticker=SQ --junitxml=tests/test-results/results.xml
      - store_test_results:
          path: tests/test-results
workflows:
  main:
    jobs:
      - test_yahoo_data
