version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test_yahoo_data:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: python -m pytest --ticker=SQ --junitxml=tests/test-results/results.xml
          name: triggering tests
      - store_test_results:
          path: tests/test-results

workflows:
  main:
    jobs:
      - test_yahoo_data
