name: Deploy app and create executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install yahooquery
          pip install yahooquery tkmacosx

      - name: Create executable
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            pyinstaller --onefile --noconsole --add-data "assets:assets" user_interface.py
          else
            echo "Unsupported OS: ${{ runner.os }}"
            exit 1
          fi

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: user_interface-${{ runner.os }}
          path: |
            dist/

      - name: Set executable permission
        if: runner.os == 'macOS'
        run: |
          chmod +x dist/user_interface

