name: Deploy app and create executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create executable
        run: |
          if [ $RUNNER_OS == "Linux" ]; then
            pyinstaller --name stock-analysis --icon=assets/charticon2ICO.ico --hidden-import=yahooquery --hidden-import=yahooquery.asyncio user_interface.py
          if [ $RUNNER_OS == "Windows" ]; then
            pyinstaller --name stock-analysis --icon=assets/charticon2ICO.ico --hidden-import=yahooquery --hidden-import=yahooquery.asyncio user_interface.py
          if [ $RUNNER_OS == "macOS" ]; then
            pyinstaller --name stock-analysis --icon=assets/charticon2ICO.ico --hidden-import=yahooquery --hidden-import=yahooquery.asyncio user_interface.py
          fi

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: stock-analysis-${{ matrix.os }}
          path: |
            dist/stock-analysis
            dist/stock-analysis.exe
            dist/stock-analysis.app
            dist/stock-analysis.bundle
            dist/stock-analysis.zip
